import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const products = [
  // Growth Hormone (7)
  {
    name: 'Ipamorelin',
    slug: 'ipamorelin',
    description: 'A selective growth hormone secretagogue that stimulates GH release without significantly affecting cortisol or prolactin levels. Studied for its role in growth hormone secretion mechanisms.',
    category: 'growth-hormone',
    price: 89.99,
    dosage: '5mg per vial',
    image: '/products/ipamorelin.png',
    researchFocus: 'Studied in relation to growth hormone secretion mechanisms and ghrelin receptor pathways.',
    productCode: 'GXL-IPA-5',
  },
  {
    name: 'CJC-1295 DAC',
    slug: 'cjc-1295-dac',
    description: 'A modified growth hormone releasing hormone (GHRH) analogue with Drug Affinity Complex for extended half-life. Researched for sustained GH elevation.',
    category: 'growth-hormone',
    price: 119.99,
    dosage: '5mg per vial',
    image: '/products/cjc-1295-dac.png',
    researchFocus: 'Extended GH release patterns and GHRH receptor binding studies.',
    productCode: 'GXL-CJC-DAC-5',
  },
  {
    name: 'CJC-1295 No DAC',
    slug: 'cjc-1295-no-dac',
    description: 'A growth hormone releasing hormone analogue without DAC modification, providing pulsatile GH release patterns. Often studied alongside GHRPs.',
    category: 'growth-hormone',
    price: 79.99,
    dosage: '5mg per vial',
    image: '/products/cjc-1295-no-dac.png',
    researchFocus: 'Pulsatile growth hormone release and synergistic GHRP interactions.',
    productCode: 'GXL-CJC-5',
  },
  {
    name: 'GHRP-2',
    slug: 'ghrp-2',
    description: 'A growth hormone releasing peptide that acts on the ghrelin receptor to stimulate GH secretion. One of the most potent GHRPs studied.',
    category: 'growth-hormone',
    price: 69.99,
    dosage: '5mg per vial',
    image: '/products/ghrp-6-glow.png',
    researchFocus: 'Ghrelin receptor signaling and growth hormone secretion amplification.',
    productCode: 'GXL-GHRP2-5',
  },
  {
    name: 'GHRP-6',
    slug: 'ghrp-6',
    description: 'A hexapeptide growth hormone releasing peptide. GHRP6 (5-amino-6-carbamoyl-hexanoyl-L-phenylalanyl-L-lysyl-L-leucyl-D-tryptophyl-L-alanyl-L-arginyl-D-phenylalaninamide). Studied for GH secretion mechanisms.',
    category: 'growth-hormone',
    price: 59.99,
    dosage: '10mg per vial',
    image: '/products/ghrp-6.png',
    researchFocus: 'Studied in relation to growth hormone secretion mechanisms and ghrelin receptor pathways.',
    productCode: 'GXL-GHRP6-10',
  },
  {
    name: 'Hexarelin',
    slug: 'hexarelin',
    description: 'A synthetic hexapeptide GH secretagogue with strong GH-releasing activity. Studied for cardiac and growth hormone applications.',
    category: 'growth-hormone',
    price: 74.99,
    dosage: '5mg per vial',
    image: '/products/hexarelin.png',
    researchFocus: 'Growth hormone release and potential cardioprotective mechanisms.',
    productCode: 'GXL-HEX-5',
  },
  {
    name: 'Sermorelin',
    slug: 'sermorelin',
    description: 'A growth hormone releasing hormone (GHRH) analogue consisting of the first 29 amino acids of GHRH. Supports lean muscle growth, recovery, and sleep research.',
    category: 'growth-hormone',
    price: 99.99,
    dosage: '5mg per vial',
    image: '/products/ipamorelin-box.png',
    researchFocus: 'Supports lean muscle growth, recovery, and sleep quality research.',
    productCode: 'GXL-SER-5',
  },

  // Metabolic (12)
  {
    name: 'AOD-9604',
    slug: 'aod-9604',
    description: 'A modified fragment of hGH (amino acids 177-191) with a tyrosine addition. Researched for fat metabolism without affecting blood sugar or growth.',
    category: 'metabolic',
    price: 89.99,
    dosage: '5mg per vial',
    image: '/products/aod-9604.png',
    researchFocus: 'Fat metabolism pathways and lipolytic activity without IGF-1 elevation.',
    productCode: 'GXL-AOD-5',
  },
  {
    name: 'Tesamorelin',
    slug: 'tesamorelin',
    description: 'A synthetic GHRH analogue researched for targeting stubborn belly fat and improving body composition through GH-mediated pathways.',
    category: 'metabolic',
    price: 149.99,
    dosage: '5mg per vial',
    image: '/products/tesamorelin.png',
    researchFocus: 'Targets stubborn belly fat and improves body composition.',
    productCode: 'GXL-TESM-5',
  },
  {
    name: 'Retatrutide',
    slug: 'retatrutide',
    description: 'A triple agonist (GIP/GLP-1/glucagon receptor) being studied for extreme weight loss, boosting energy, and supporting liver and kidney research.',
    category: 'metabolic',
    price: 219.99,
    dosage: '10mg per vial',
    image: '/products/retatrutide.png',
    researchFocus: 'Extreme weight loss, boosts energy, liver and kidney support research.',
    productCode: 'GXL-RET-10',
  },
  {
    name: 'Tirzepatide',
    slug: 'tirzepatide',
    description: 'A dual GIP/GLP-1 receptor agonist studied for appetite suppression, fat loss, and improved insulin sensitivity research.',
    category: 'metabolic',
    price: 199.99,
    dosage: '10mg per vial',
    image: '/products/tirzepatide.png',
    researchFocus: 'Suppresses appetite, supports fat loss, and improves insulin sensitivity.',
    productCode: 'GXL-TIRZ-10',
  },
  {
    name: 'MOTS-c',
    slug: 'mots-c',
    description: 'A mitochondrial-derived peptide that regulates metabolic homeostasis. Researched for boosting metabolism, energy levels, and fat burning.',
    category: 'metabolic',
    price: 129.99,
    dosage: '10mg per vial',
    image: '/products/mots-c.png',
    researchFocus: 'Boosts metabolism, energy levels, and burns fat.',
    productCode: 'GXL-MOTS-10',
  },
  {
    name: 'Mazdutide',
    slug: 'mazdutide',
    description: 'A dual GLP-1/glucagon receptor agonist researched for weight loss and glucose regulation in metabolic studies.',
    category: 'metabolic',
    price: 179.99,
    dosage: '10mg per vial',
    image: '/products/tirzepatide-wholesale.png',
    researchFocus: 'Supports weight loss and glucose regulation.',
    productCode: 'GXL-MAZ-10',
  },
  {
    name: 'SLU-DP-322',
    slug: 'slu-dp-322',
    description: 'A novel research compound studied for enhancing fat burning and energy output through metabolic pathway modulation.',
    category: 'metabolic',
    price: 159.99,
    dosage: '10mg per vial',
    image: '/products/slu-dp-322.png',
    researchFocus: 'Enhances fat burning and energy output.',
    productCode: 'GXL-SLU-10',
  },
  {
    name: 'Survodutide',
    slug: 'survodutide',
    description: 'A dual glucagon/GLP-1 receptor agonist being researched for weight loss and metabolic regulation.',
    category: 'metabolic',
    price: 189.99,
    dosage: '10mg per vial',
    image: '/products/tirzepatide-caps.png',
    researchFocus: 'Supports weight loss and metabolic regulation.',
    productCode: 'GXL-SURV-10',
  },
  {
    name: '5-Amino-1MQ',
    slug: '5-amino-1mq',
    description: 'A small molecule NNMT inhibitor researched for boosting energy, increasing metabolism, and promoting fat burning through NAD+ pathway modulation.',
    category: 'metabolic',
    price: 99.99,
    dosage: '50mg capsules',
    image: '/products/5-amino-1mq.png',
    researchFocus: 'Boosts energy, increases metabolism, and burns fat.',
    productCode: 'GXL-5A1MQ-50',
  },
  {
    name: 'Fragment 176-191',
    slug: 'fragment-176-191',
    description: 'The fat-reducing segment of human growth hormone. Studied for lipolysis and fat metabolism without the growth-promoting effects of full-length hGH.',
    category: 'metabolic',
    price: 79.99,
    dosage: '5mg per vial',
    image: '/products/aod-9604-single.png',
    researchFocus: 'Lipolysis and fat metabolism research.',
    productCode: 'GXL-FRAG-5',
  },
  {
    name: 'Cagrilintide',
    slug: 'cagrilintide',
    description: 'A long-acting amylin analogue researched for appetite regulation and weight management through central nervous system pathways.',
    category: 'metabolic',
    price: 169.99,
    dosage: '10mg per vial',
    image: '/products/retatrutide-cagrilintide.png',
    researchFocus: 'Appetite regulation and weight management research.',
    productCode: 'GXL-CAG-10',
  },

  {
    name: 'Semaglutide',
    slug: 'semaglutide',
    description: 'A GLP-1 receptor agonist researched for appetite regulation, weight management, and glucose homeostasis. One of the most studied incretin mimetics.',
    category: 'metabolic',
    price: 189.99,
    dosage: '3mg capsules',
    image: '/products/semaglutide-caps.png',
    researchFocus: 'Appetite regulation, weight management, and glucose homeostasis research.',
    productCode: 'GXL-SEMA-3',
  },

  // Neuropeptide (3)
  {
    name: 'Semax',
    slug: 'semax',
    description: 'A synthetic peptide derived from ACTH (4-10) with added Pro-Gly-Pro sequence. Researched for enhancing focus, memory, mood, and mental clarity.',
    category: 'neuropeptide',
    price: 69.99,
    dosage: '5mg per vial',
    image: '/products/semax.png',
    researchFocus: 'Enhances focus, memory, mood, and mental clarity.',
    productCode: 'GXL-SEM-5',
  },
  {
    name: 'Selank',
    slug: 'selank',
    description: 'A synthetic analogue of the immunomodulatory peptide tuftsin. Researched for reducing anxiety, improving mood, and sharpening focus.',
    category: 'neuropeptide',
    price: 69.99,
    dosage: '5mg per vial',
    image: '/products/selank.png',
    researchFocus: 'Reduces anxiety, improves mood, and sharpens focus.',
    productCode: 'GXL-SEL-5',
  },
  {
    name: 'DSIP',
    slug: 'dsip',
    description: 'Delta Sleep Inducing Peptide — a neuropeptide researched for sleep regulation, stress reduction, and circadian rhythm modulation.',
    category: 'neuropeptide',
    price: 59.99,
    dosage: '5mg per vial',
    image: '/products/semax-multi.png',
    researchFocus: 'Sleep regulation, stress reduction, and circadian rhythm research.',
    productCode: 'GXL-DSIP-5',
  },

  // Tissue & Repair (3)
  {
    name: 'BPC-157',
    slug: 'bpc-157',
    description: 'Body Protection Compound — a pentadecapeptide derived from gastric juice. Extensively studied for tissue healing, gut repair, and anti-inflammatory properties.',
    category: 'tissue-repair',
    price: 79.99,
    dosage: '10mg per vial',
    image: '/products/bpc-157.png',
    researchFocus: 'Tissue healing, gut repair, and anti-inflammatory pathway research.',
    productCode: 'GXL-BPC-10',
  },
  {
    name: 'TB-500',
    slug: 'tb-500',
    description: 'A synthetic version of thymosin beta-4. Researched for muscle repair, flexibility, reduced inflammation, and wound healing acceleration.',
    category: 'tissue-repair',
    price: 89.99,
    dosage: '10mg per vial',
    image: '/products/thymosin-box.png',
    researchFocus: 'Supports muscle repair, flexibility, and reduces inflammation.',
    productCode: 'GXL-TB500-10',
  },
  {
    name: 'Thymosin Alpha-1',
    slug: 'thymosin-alpha-1',
    description: 'A thymic peptide with immunomodulatory properties. Studied for immune system enhancement and modulation of T-cell function.',
    category: 'tissue-repair',
    price: 99.99,
    dosage: '5mg per vial',
    image: '/products/thymosin-alpha-1.png',
    researchFocus: 'Immune system enhancement and T-cell function modulation.',
    productCode: 'GXL-TA1-5',
  },

  // Anti-aging (4)
  {
    name: 'NAD+',
    slug: 'nad-plus',
    description: 'Nicotinamide Adenine Dinucleotide — a coenzyme researched for brain function, energy production, and healthy anti-aging pathways.',
    category: 'anti-aging',
    price: 149.99,
    dosage: '500mg per vial',
    image: '/products/nad-plus.png',
    researchFocus: 'Supports brain function, energy production, and healthy anti-aging.',
    productCode: 'GXL-NAD-500',
  },
  {
    name: 'Epithalon',
    slug: 'epithalon',
    description: 'A synthetic tetrapeptide based on epithalamine. Researched for telomerase activation and cellular aging mechanisms.',
    category: 'anti-aging',
    price: 109.99,
    dosage: '10mg per vial',
    image: '/products/thymosin-alpha-1-blue.png',
    researchFocus: 'Telomerase activation and cellular longevity research.',
    productCode: 'GXL-EPIT-10',
  },
  {
    name: 'L-Glutathione',
    slug: 'l-glutathione',
    description: 'The master antioxidant. Researched for detox support, immune system function, and skin radiance through oxidative stress reduction.',
    category: 'anti-aging',
    price: 89.99,
    dosage: '200mg per vial',
    image: '/products/l-glutathione.png',
    researchFocus: 'Supports detox, immune system, and skin radiance.',
    productCode: 'GXL-GLUT-200',
  },

  {
    name: 'GHK-Cu',
    slug: 'ghk-cu',
    description: 'A naturally occurring copper peptide with powerful regenerative properties. Researched for skin remodeling, wound healing, and anti-aging through collagen synthesis and antioxidant gene activation.',
    category: 'anti-aging',
    price: 79.99,
    dosage: '50mg per vial',
    image: '/products/ghk-cu.png',
    researchFocus: 'Skin remodeling, collagen synthesis, and antioxidant gene activation research.',
    productCode: 'GXL-GHKCU-50',
  },

  // Growth Factor (4)
  {
    name: 'IGF-1 LR3',
    slug: 'igf-1-lr3',
    description: 'A modified insulin-like growth factor with extended half-life. Researched for muscle growth, recovery, and anabolic signaling pathways.',
    category: 'growth-factor',
    price: 199.99,
    dosage: '1mg per vial',
    image: '/products/igf-1-lr3.png',
    researchFocus: 'Muscle growth, recovery, and IGF signaling pathway research.',
    productCode: 'GXL-IGF1LR3-1',
  },
  {
    name: 'IGF-1 DES',
    slug: 'igf-1-des',
    description: 'A truncated form of IGF-1 lacking the first 3 amino acids. 10x more potent than standard IGF-1 for localized tissue research.',
    category: 'growth-factor',
    price: 179.99,
    dosage: '1mg per vial',
    image: '/products/igf-1-lr3.png',
    researchFocus: 'Localized tissue growth and enhanced IGF receptor binding research.',
    productCode: 'GXL-IGF1DES-1',
  },
  {
    name: 'PEG-MGF',
    slug: 'peg-mgf',
    description: 'PEGylated Mechano Growth Factor — a splice variant of IGF-1 with PEG modification for systemic research applications.',
    category: 'growth-factor',
    price: 159.99,
    dosage: '2mg per vial',
    image: '/products/ghk-cu-multi.png',
    researchFocus: 'Muscle satellite cell activation and systemic growth factor research.',
    productCode: 'GXL-PEGMGF-2',
  },
  {
    name: 'Follistatin-344',
    slug: 'follistatin-344',
    description: 'A glycoprotein that inhibits myostatin and activin. Researched for muscle growth potential and myostatin regulation.',
    category: 'growth-factor',
    price: 249.99,
    dosage: '1mg per vial',
    image: '/products/mots-c-multi.png',
    researchFocus: 'Myostatin inhibition and muscle growth regulation research.',
    productCode: 'GXL-FOLL-1',
  },

  // Stacks (3)
  {
    name: 'Wolverine Stack (BPC-157 + TB-500)',
    slug: 'wolverine-stack',
    description: 'Recovery stack combining BPC-157 and TB-500. Accelerates healing, reduces inflammation, and supports injury repair research.',
    category: 'stacks',
    price: 149.99,
    dosage: '10mg BPC-157 + 10mg TB-500',
    image: '/products/wolverine-stack.png',
    researchFocus: 'Recovery stack: accelerates healing, reduces inflammation, and supports injury repair.',
    productCode: 'GXL-WOLF-STACK',
  },
  {
    name: 'CJC-1295 + Ipamorelin Stack',
    slug: 'cjc-ipamorelin-stack',
    description: 'A synergistic GH secretagogue stack combining CJC-1295 No DAC with Ipamorelin for optimized growth hormone release research.',
    category: 'stacks',
    price: 139.99,
    dosage: '5mg CJC-1295 + 5mg Ipamorelin',
    image: '/products/cjc-1295-dac-multi.png',
    researchFocus: 'Synergistic growth hormone release and GHRH/GHRP pathway research.',
    productCode: 'GXL-CJCIPA-STACK',
  },
  {
    name: 'Tesamorelin + 5-Amino-1MQ Stack',
    slug: 'tesamorelin-5amino-stack',
    description: 'A metabolic optimization stack combining Tesamorelin with 5-Amino-1MQ for enhanced fat metabolism and body composition research.',
    category: 'stacks',
    price: 219.99,
    dosage: '5mg Tesamorelin + 50mg 5-Amino-1MQ',
    image: '/products/tesamorelin-multi.png',
    researchFocus: 'Fat metabolism optimization and body composition improvement research.',
    productCode: 'GXL-TES5A-STACK',
  },

  // Other (4)
  {
    name: 'Melanotan II',
    slug: 'melanotan-ii',
    description: 'A synthetic analogue of alpha-MSH. Researched for melanocortin receptor activation, skin tanning pathways, and libido studies.',
    category: 'other',
    price: 69.99,
    dosage: '10mg per vial',
    image: '/products/mots-c-box.png',
    researchFocus: 'Enhances skin tanning and libido research.',
    productCode: 'GXL-MT2-10',
  },
  {
    name: 'PT-141',
    slug: 'pt-141',
    description: 'Bremelanotide — a melanocortin receptor agonist researched for sexual dysfunction pathways and central nervous system arousal mechanisms.',
    category: 'other',
    price: 79.99,
    dosage: '10mg per vial',
    image: '/products/pt-141.png',
    researchFocus: 'Sexual function pathways and melanocortin receptor research.',
    productCode: 'GXL-PT141-10',
  },
  {
    name: 'Kisspeptin-10',
    slug: 'kisspeptin-10',
    description: 'A neuropeptide that regulates the HPG axis and gonadotropin release. Researched for reproductive endocrinology and hormone regulation.',
    category: 'other',
    price: 89.99,
    dosage: '5mg per vial',
    image: '/products/kisspeptin-10.png',
    researchFocus: 'HPG axis regulation and reproductive endocrinology research.',
    productCode: 'GXL-KISS-5',
  },
  {
    name: 'Vitamin B-12',
    slug: 'vitamin-b12',
    description: 'Methylcobalamin (B12) research compound. Studied for energy metabolism, neurological function, and methylation pathway support.',
    category: 'other',
    price: 49.99,
    dosage: '5000mcg per vial',
    image: '/products/vitamin-b12.png',
    researchFocus: 'Energy metabolism and neurological function research.',
    productCode: 'GXL-B12-5000',
  },
]

async function main() {
  console.log('Seeding products...')

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
    console.log(`  Seeded: ${product.name}`)
  }

  console.log(`\nDone! Seeded ${products.length} products.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
